name: brewtoob
favicon: null
layout_spectrum: 0.2959111467935145
typography_spectrum: 0.19960981979966164
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3773274328559637
  lightness: 0.8118831187020987
  saturation: 0.4859169600531459
  rhythmicContrast: 0.37195940525271
purpose: []
